# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123Pass
      - POSTGRES_DB=Nest
    ports:
      - '5432:5432'